server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taobao?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=true&useOldAliasMetadataBehavior=true
    username: root
    password: 123
  jpa:
    database: MySQL
    #在建表的时候，将默认的存储引擎切换为 InnoDB
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # 配置在日志中打印出执行的 SQL 语句信息。
    show-sql: true
    # 配置指明在程序启动的时候要删除并且创建实体类对应的表。

    hibernate:
      naming:
        # 遇到大写字母直接加 _ 的命名
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      # PhysicalNamingStrategyStandardImpl不做修改，直接映射

      ddl-auto: update
  #        create：每次运行程序时，都会重新创建表，故而数据会丢失
  #        create-drop：每次运行程序时会先创建表结构，然后待程序结束时清空表
  #        upadte：每次运行程序，没有表时会创建表，如果对象发生改变会更新表结构，原有数据不会清空，只会更新（推荐使用）
  #        validate：运行程序会校验数据与数据库的字段类型是否相同，字段不同会报错
  #        none: 禁用DDL处理

  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: utf-8
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.bs.agricultural_share_platform.model

#分页
#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql
#  retrunPageInfo: check



